routes/web.php
<?php
use App\Http\Controllers\PostController;
use App\Http\Controllers\MainController;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix'=>'account','middleware'=>['auth']],function(){
    Route::get('/', 'UserController@cabinet');
});
Auth::routes();

Route::post('/edit', 'UserController@updateUser')->name('user_name');
Route::post('/edit-email', 'UserController@updateEmail')->name('user_email');
Route::post('/',[PostController::class,'Submit'])->name('form-input');

Route::post('/predmets/rus', 'PredmetController@AddRus')->name('rus');
Route::post('/predmets/math', 'PredmetController@AddMath')->name('math');
Route::post('/predmets/inform', 'PredmetController@AddInform')->name('inform');
Route::post('/predmets/eng', 'PredmetController@AddEng')->name('eng');
Route::post('/predmets/del/{predmet}', 'PredmetController@Delete');
Route::get('/1', 'ZadaniyaController@rus');
Route::get('/2', 'ZadaniyaController@eng');
Route::get('/3', 'ZadaniyaController@math');
Route::get('/4', 'ZadaniyaController@inform');
Auth::routes();

Route::resource('/task','ZadaniyaController');
Route::get('/predmets', 'PredmetController@predmets')->name('predm');

Route::get('/', 'PostController@Output')->name('home');
Route::get('/instruction', 'PostController@selectRules')->name('pechat');
Route::get('/addnews', 'MainController@addnews')->name('addnews');
Route::get('logout','Auth\LoginController@logout');
Route::group(['prefix'=>'admin','middleware'=>['auth']],function(){
    Route::get('/', [App\Http\Controllers\Admin\HomeController::class,'index'])->name('home_admin');
});
Route::resource('category',Admin\CategController::class);
Route::resource('post',Admin\PostsController::class);
Route::post('/send-foto','MainController@update')->name('form-foto');

Route::group(['middleware'=>'auth','prefix'=>'unit','namespace'=>'App\Http\Controllers'],function(){
    Route::get('test',function(){
        return response()->json(['ok'],200);
    });
});

app/Post.php
<?php

namespace App;

use App\Filters\QueryFilter;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    /**
 * The table associated with the model.
 *
 * @var string
 */
protected $table = 'post';
    public function category(){
        return $this->belongsTo('App\Categor','cat_id','id');
    }
    public function scopeFilter(Builder $builder, QueryFilter $filter){
        return $filter->apply($builder);
    }
}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Post;
use App\Categor;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(User $user)
    {
        
        Gate::authorize('adminka',[$user]);
        $posts = Post::orderBy('created_at', 'DESC')->get();

        return view('admin.post.index', [
            'posts' => $posts
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(User $user)
    {
        
        Gate::authorize('adminka',[$user]);
        $categories = Categor::orderBy('created_at', 'DESC')->get();

        return view('admin.post.create', [
            'categories' => $categories
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $body=$request->body;
        $name=$request->name;
        $cat=$request->cat_id;
        $data = $request->all();
        if(empty($request->cat_id)){
            $cat=3;
        }
        $filename= date('YmdHis')."-".$data['image']->getClientOriginalName();

        //Сохраняем оригинальную картинку
        $data['image']->move(Storage::path('/public/storage/image/news/').'origin/',$filename);

        //Создаем миниатюру изображения и сохраняем ее
        $thumbnail = Image::make(Storage::path('/public/storage/image/news/').'origin/'.$filename);
        $thumbnail->fit(300, 300);
        $thumbnail->save(Storage::path('/public/storage/image/news/').'thumbnail/'.$filename);

        //Сохраняем новость в БД
        $data['image'] = $filename;
        DB::table('post')->insert(['name'=>$name,'body'=>$body,'image'=>$data['image'],'cat_id'=>$cat,'created_at'=>date('Y-m-d H:i:s')]);

        return redirect()->back()->withSuccess('Статья была успешно обновлена!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post,User $user)
    {
        Gate::authorize('adminka',[$user]);
        $categories = Categor::orderBy('created_at', 'DESC')->get();

        return view('admin.post.edit', [
            'categories' => $categories,
            'post' => $post,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $data = $request->all();
        if(empty($request->cat_id)){
            $cat=3;
        }
        if(!empty($data['image'])){
        $filename= date('YmdHis')."-".$data['image']->getClientOriginalName();

        //Сохраняем оригинальную картинку
        $data['image']->move(Storage::path('/public/storage/image/news/').'origin/',$filename);

        //Создаем миниатюру изображения и сохраняем ее
        $thumbnail = Image::make(Storage::path('/public/storage/image/news/').'origin/'.$filename);
        $thumbnail->fit(300, 300);
        $thumbnail->save(Storage::path('/public/storage/image/news/').'thumbnail/'.$filename);
        $data['image'] = $filename;
        $post->image = $data['image'];
        }
        //Сохраняем новость в БД
       
        $post->name = $request->name;
        $post->body = $request->body;
        $post->cat_id = $request->cat_id;
        $post->save();

        return redirect()->back()->withSuccess('Статья была успешно обновлена!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        
        $post->delete();
        return redirect()->back()->withSuccess('Статья была успешно удалена!');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\PostRequest;
use Illuminate\Http\Request;
use App\Categor;
use App\Post;
use App\Filters\PostFilter;
class PostController extends Controller
{
    public function Submit(PostRequest $req){
        $body=$req->body;
        $name=$req->name;
        $cat=$req->category_id;
        $data = $req->all();
        if(empty($req->category_id)){
            $cat=3;
        }
        
        $filename= date('YmdHis')."-".$data['image']->getClientOriginalName();

        //Сохраняем оригинальную картинку
        $data['image']->move(Storage::path('/public/storage/image/news/').'origin/',$filename);

        //Создаем миниатюру изображения и сохраняем ее
        $thumbnail = Image::make(Storage::path('/public/storage/image/news/').'origin/'.$filename);
        $thumbnail->fit(300, 300);
        $thumbnail->save(Storage::path('/public/storage/image/news/').'thumbnail/'.$filename);

        //Сохраняем новость в БД
        $data['image'] = $filename;
        DB::table('post')->insert(['name'=>$name,'body'=>$body,'image'=>$data['image'],'cat_id'=>$cat,'created_at'=>date('Y-m-d H:i:s')]);
        return redirect()->back()->withSuccess('Успешно! Добавлена новость.');
        
    }
    public function Output(PostFilter $request){
        
        $posts=Post::orderBy('created_at', 'DESC')->filter($request)->paginate(9);
        
        $categories=Categor::orderBy('created_at', 'DESC')->get();

        return view('home', compact(['posts','categories']));
    }
    public function selectRules(){
        return view('print');
    }
}

resources/views/admin/post/create.blade.php
@extends('layouts.admin')

@section('title', 'Добавить статью')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Добавить статью</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                </div>
            @endif
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-primary">
                        <!-- form start -->
                        <form action="{{ route('post.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Название</label>
                                    <input type="text" name="name" class="form-control" id="exampleInputEmail1"
                                        placeholder="Введите название статьи" required>
                                </div>
                                <div class="form-group">
                                    <!-- select -->
                                    <div class="form-group">
                                        <label>Выберите категорию</label>
                                        <select name="cat_id" class="form-control" required>
                                            @foreach ($categories as $category)
                                                <option value="{{ $category['id'] }}">{{ $category['name'] }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="body">Содержание</label>
                                    <textarea class="form-control" rows="3" name="body"></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="image">Картинка для новости</label>
                                    <input type="file" class="form-control-file" id="image" name="image">
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Добавить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/post/edit.blade.php
@extends('layouts.admin')

@section('title', 'Редактировать статью')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Редактировать статью: {{ $post['name'] }}</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                </div>
            @endif
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-primary">
                        <!-- form start -->
                        <form action="{{ route('post.update', $post['id']) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Название</label>
                                    <input type="text" value="{{ $post['name'] }}" name="name" class="form-control"
                                        id="exampleInputEmail1" placeholder="Введите название статьи" required>
                                </div>
                                <div class="form-group">
                                    <!-- select -->
                                    <div class="form-group">
                                        <label>Выберите категорию</label>
                                        <select name="cat_id" class="form-control" required>
                                            @foreach ($categories as $category)
                                                <option value="{{ $category['id'] }}" @if ($category['id'] == $post['cat_id']) selected
                                            @endif>{{ $category['name'] }}
                                            </option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="body">Содержание</label>
                                    <textarea class="form-control" rows="3" name="body">{{ $post['body'] }}</textarea>
                                </div>
                                <div class="form-group">
                                    <label for="image">Картинка для новости</label>
                                    <img src="/storage/storage/image/news/origin/{{ $post->image }}" alt="{{ $post->image}}" class="img-uploaded" style="display: block; width: 300px">
                                    <input type="file" value="{{ $post->image}}" class="form-control-file" id="image" name="image">
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/post/index.blade.php
@extends('layouts.admin')

@section('title', 'Все статьи')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Все статьи</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                </div>
            @endif
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body p-0">
                    <table class="table table-striped projects">
                        <thead>
                            <tr>
                                <th style="width: 5%">
                                    ID
                                </th>
                                <th>
                                    Название
                                </th>
                                <th>
                                    Категория
                                </th>
                                <th>
                                    Дата добавления
                                </th>
                                <th style="width: 30%">
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($posts as $post)
                                <tr>
                                    <td>
                                        {{ $post->id }}
                                    </td>
                                    <td>
                                        {{ $post->name }}
                                    </td>
                                    <td>
                                        {{ $post->category->name }}
                                    </td>
                                    <td>
                                        {{ $post->created_at}}
                                    </td>

                                    <td class="project-actions text-right">
                                        <a class="btn btn-info btn-sm" href="{{ route('post.edit', $post['id']) }}">
                                            <i class="fas fa-pencil-alt">
                                            </i>
                                            Редактировать
                                        </a>
                                        <form action="{{ route('post.destroy', $post['id']) }}" method="POST"
                                            style="display: inline-block">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm delete-btn">
                                                <i class="fas fa-trash">
                                                </i>
                                                Удалить
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach


                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection