routes/web.php
<?php
use App\Http\Controllers\PostController;
use App\Http\Controllers\MainController;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix'=>'account','middleware'=>['auth']],function(){
    Route::get('/', 'UserController@cabinet');
});
Auth::routes();

Route::post('/edit', 'UserController@updateUser')->name('user_name');
Route::post('/edit-email', 'UserController@updateEmail')->name('user_email');
Route::post('/',[PostController::class,'Submit'])->name('form-input');

Route::post('/predmets/rus', 'PredmetController@AddRus')->name('rus');
Route::post('/predmets/math', 'PredmetController@AddMath')->name('math');
Route::post('/predmets/inform', 'PredmetController@AddInform')->name('inform');
Route::post('/predmets/eng', 'PredmetController@AddEng')->name('eng');
Route::post('/predmets/del/{predmet}', 'PredmetController@Delete');
Route::get('/1', 'ZadaniyaController@rus');
Route::get('/2', 'ZadaniyaController@eng');
Route::get('/3', 'ZadaniyaController@math');
Route::get('/4', 'ZadaniyaController@inform');
Auth::routes();

Route::resource('/task','ZadaniyaController');
Route::get('/predmets', 'PredmetController@predmets')->name('predm');

Route::get('/', 'PostController@Output')->name('home');
Route::get('/instruction', 'PostController@selectRules')->name('pechat');
Route::get('/addnews', 'MainController@addnews')->name('addnews');
Route::get('logout','Auth\LoginController@logout');
Route::group(['prefix'=>'admin','middleware'=>['auth']],function(){
    Route::get('/', [App\Http\Controllers\Admin\HomeController::class,'index'])->name('home_admin');
});
Route::resource('category',Admin\CategController::class);
Route::resource('post',Admin\PostsController::class);
Route::post('/send-foto','MainController@update')->name('form-foto');

Route::group(['middleware'=>'auth','prefix'=>'unit','namespace'=>'App\Http\Controllers'],function(){
    Route::get('test',function(){
        return response()->json(['ok'],200);
    });
});

app/Http/Controllers/Admin/HomeController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Post;
use App\Categor;
use App\User;
use Illuminate\Support\Facades\Gate;

class HomeController extends Controller
{
    function index(User $user){
        
        Gate::authorize('adminka',[$user]);
        $posts_count = Post::all()->count();
        $categories_count = Categor::all()->count();
        $users_count = User::all()->count();
        $user_admin = User::where(
            'role_id','=','1'
            )->count();
        $user_teach = User::where(
                'role_id','=','2'
        )->count();
        $user_ychen = User::where(
                    'role_id','=','3'
        )->count();
        $users=User::all()->count();
        $pro_admin=(int)(100/$users * $user_admin+0.49);
        $pro_teach=(int)(100/$users*$user_teach+0.49);
        $pro_ychen=(int)(100/$users*$user_ychen+0.49);
        $posts_one = Post::where('cat_id','=','1')->count();
        $posts_two = Post::where('cat_id','=','2')->count();
        $posts_three = Post::where('cat_id','=','3')->count();
        $posts_four = Post::where('cat_id','=','4')->count();
        $posts_five = Post::where('cat_id','=','7')->count();
        $for_one=(int)($posts_one*100/$posts_count+0.49);
        $for_two=(int)($posts_two/$posts_count*100+0.49);
        $for_three=(int)($posts_three/$posts_count*100+0.49);
        $for_four=(int)($posts_four/$posts_count*100+0.49);
        $for_five=(int)($posts_five/$posts_count*100+0.49);


        return view('admin.home.index', [
            'posts_count' => $posts_count,
            'users_count' => $users_count,
            'categories_count' => $categories_count,
            'user_admin'=>$user_admin,
            'user_teach'=>$user_teach,
            'user_ychen'=>$user_ychen,
            'pro_admin'=>$pro_admin,
            'pro_teach'=>$pro_teach,
            'pro_ychen'=>$pro_ychen,
            'posts_one'=>$posts_one,
            'posts_two'=>$posts_two,
            'posts_three'=>$posts_three,
            'posts_four'=>$posts_four,
            'posts_five'=>$posts_five,
            'for_one'=>$for_one,
            'for_two'=>$for_two,
            'for_three'=>$for_three,
            'for_four'=>$for_four,
            'for_five'=>$for_five,
        ]);
    }
    
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
}

resources/views/admin/home/category.blade.php
@extends('layouts.admin')

@section('title', 'Все категории')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Все категории</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                </div>
            @endif
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body p-0">
                    <table class="table table-striped projects">
                        <thead>
                            <tr>
                                <th style="width: 5%">
                                    ID
                                </th>
                                <th>
                                    Название
                                </th>
                                <th style="width: 30%">
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($categories as $category)
                                <tr>
                                    <td>
                                        {{ $category['id'] }}
                                    </td>
                                    <td>
                                        {{ $category['name'] }}
                                    </td>

                                    <td class="project-actions text-right">
                                        <a class="btn btn-info btn-sm" href="{{ route('category.edit', $category['id']) }}">
                                            <i class="fas fa-pencil-alt">
                                            </i>
                                            Редактировать
                                        </a>
                                        <form action="{{ route('category.destroy', $category['id']) }}" method="POST"
                                            style="display: inline-block">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm delete-btn">
                                                <i class="fas fa-trash">
                                                </i>
                                                Удалить
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach


                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/home/create.blade.php
@extends('layouts.admin')
@section('title','Добавить категорию')
 
@section('content')
  <!-- Content Header (Page header) -->
  <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Добавить категорию</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                </div>
            @endif
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-primary">
                        <!-- form start -->
                        <form action="{{ route('category.store') }}" method="POST">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Название</label>
                                    <input type="text" name="name" class="form-control" id="exampleInputEmail1"
                                        placeholder="Введите название категории" required>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Добавить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/home/edit.blade.php
@extends('layouts.admin')

@section('title', 'Редактирование категории')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Редактирование категории: {{ $category->name}}</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                </div>
            @endif
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-primary">
                        <!-- form start -->
                        <form action="{{ route('category.update', $category->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Название</label>
                                    <input type="text" value="{{ $category->name }}" name="name" class="form-control"
                                        id="exampleInputEmail1" placeholder="Введите название категории" required>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Обновить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/home/index.blade.php
@extends('layouts.admin')
@section('title','Главная')
 
@section('content')

<!-- Content Header (Page header) -->
<div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Главная</h1>
          </div><!-- /.col -->
          
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3>{{$posts_count}}</h3>

                <p>Количество новостей</p>
              </div>
              <div class="icon">
                <i class="ion ion-bag"></i>
              </div>
              <a href="{{route('post.index')}}" class="small-box-footer">Все статьи<i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>{{$categories_count}}</h3>

                <p>Количество категорий</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="{{route('category.index')}}" class="small-box-footer">Все статьи <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
              <div class="inner">
                <h3>{{$users_count}}</h3>

                <p>Количество пользователей</p>
              </div>
              <div class="icon">
                <i class="ion ion-person-add"></i>
              </div>
              <a href="#" class="small-box-footer">Раздел пока недоступен</a>
            </div>
          </div>
        </div>
        
    <h3 class="m-0">Пользователи по категориям</h3>
        <div class="chart">
        <p class="chart__block">Администраторы - {{$user_admin}} ({{$pro_admin}}%)</p>
        <div class="pipe">
        <div style="width: {{$pro_admin}}%"> </div>
        </div>
        
        <p>Учителя - {{$user_teach}} ({{$pro_teach}}%)</p>
        <div class="pipe">
        <div style="width: {{$pro_teach}}%"> </div>
        </div>
        <p>Ученики - {{$user_ychen}} ({{$pro_ychen}}%)</p>
        <div class="pipe">
        <div style="width: {{$pro_ychen}}%"> </div>
        </div>
    </div>
    <h3 class="m-0">Новости по категориям</h3>
    <div id="graph" class="graph vertical">
          <div class="item" style="height:{{$for_one}}px">{{$posts_one}} ({{$for_one}}%)</div><p class="vertic">Достижения</p>
          <div class="item" style="height:{{$for_two}}px">{{$posts_two}} ({{$for_two}}%)</div><p class="vertic">Научные факты</p>
          <div class="item" style="height:{{$for_three}}px">{{$posts_three}} ({{$for_three}}%)</div><p class="vertic">Нет Категории</p>
          <div class="item" style="height:{{$for_four}}px">{{$posts_four}} ({{$for_four}}%)</div><p class="vertic"> Творчество</p>
          <div class="item" style="height:{{$for_five}}px">{{$posts_five}} ({{$for_five}}%)</div><p class="vertic">Полезное</p>
    </div>
  @endsection