routes/web.php
<?php
use App\Http\Controllers\PostController;
use App\Http\Controllers\MainController;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix'=>'account','middleware'=>['auth']],function(){
    Route::get('/', 'UserController@cabinet');
});
Auth::routes();

Route::post('/edit', 'UserController@updateUser')->name('user_name');
Route::post('/edit-email', 'UserController@updateEmail')->name('user_email');
Route::post('/',[PostController::class,'Submit'])->name('form-input');

Route::post('/predmets/rus', 'PredmetController@AddRus')->name('rus');
Route::post('/predmets/math', 'PredmetController@AddMath')->name('math');
Route::post('/predmets/inform', 'PredmetController@AddInform')->name('inform');
Route::post('/predmets/eng', 'PredmetController@AddEng')->name('eng');
Route::post('/predmets/del/{predmet}', 'PredmetController@Delete');
Route::get('/1', 'ZadaniyaController@rus');
Route::get('/2', 'ZadaniyaController@eng');
Route::get('/3', 'ZadaniyaController@math');
Route::get('/4', 'ZadaniyaController@inform');
Auth::routes();

Route::resource('/task','ZadaniyaController');
Route::get('/predmets', 'PredmetController@predmets')->name('predm');

Route::get('/', 'PostController@Output')->name('home');
Route::get('/instruction', 'PostController@selectRules')->name('pechat');
Route::get('/addnews', 'MainController@addnews')->name('addnews');
Route::get('logout','Auth\LoginController@logout');
Route::group(['prefix'=>'admin','middleware'=>['auth']],function(){
    Route::get('/', [App\Http\Controllers\Admin\HomeController::class,'index'])->name('home_admin');
});
Route::resource('category',Admin\CategController::class);
Route::resource('post',Admin\PostsController::class);
Route::post('/send-foto','MainController@update')->name('form-foto');

Route::group(['middleware'=>'auth','prefix'=>'unit','namespace'=>'App\Http\Controllers'],function(){
    Route::get('test',function(){
        return response()->json(['ok'],200);
    });
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Админ-панель @yield('title')</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- JQVMap -->
  <link rel="stylesheet" href="/plugins/jqvmap/jqvmap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/dist/css/graphick.css">
  <link rel="stylesheet" href="/dist/css/adminlte.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="/plugins/daterangepicker/daterangepicker.css">
  <!-- summernote -->
  <link rel="stylesheet" href="/plugins/summernote/summernote-bs4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="/dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
  </div>

<button class="menu__button" id="example_2_1" onclick="document.getElementById('example_2').style.marginLeft='0'; document.getElementById('example_2_1').style.marginLeft='0'; document.getElementById('example_2_2').style.marginLeft='0';" style="display:block;">→</button>

  <!-- Main Sidebar Container -->
  <aside id="example_2"  class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    
<button class="menu__button" id="example_2_2" onclick=" document.getElementById('example_2').style.marginLeft='-250px'; document.getElementById('example_2_2').style.marginLeft='-150px'; document.getElementById('example_2_1').style.display='block';">←</button>
    <a href="{{route('home_admin')}}" class="brand-link">
      <img src="/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Админ панель</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="{{url('/account')}}" class="d-block">{{Auth::user()->name}}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
            <li class="nav-item">
                <a href="{{route('home_admin')}}" class="nav-link">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                    Главная
                </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{route('home')}}" class="nav-link">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                    На сайт
                </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                <i class="nav-icon far fa-newspaper"></i>
                <p>
                    Блог
                    
                <i class="right fas fa-angle-left"></i>
                </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{route('post.index')}}" class="nav-link">

                        <p>
                            Все статьи
                        </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('post.create')}}" class="nav-link">
                        <p>
                            Добавить статью
                        </p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                <i class="nav-icon fas fa-align-left"></i>
                <p>
                    Категории
                    
                    <i class="right fas fa-angle-left"></i>
                </p>
                </a>
                
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{route('category.index')}}" class="nav-link">
                        <p>
                            Все Категории
                        </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('category.create')}}" class="nav-link">
                        <p>
                            Добавить категорию
                        </p>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
<div class="content-wrapper">
    @yield('content')
</div>


  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="/plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="/plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="/plugins/moment/moment.min.js"></script>
<script src="/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="/dist/js/adminlte.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/dist/js/demo.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="/dist/js/pages/dashboard.js"></script>
<script src="/admin.js"></script>
<script src="https://cdn.tiny.cloud/1/jxsqeq85qzdwuqqqruya91jqsrhqtxykhxtks6sn0t1kn69g/tinymce/5/tinymce.min.js"
        referrerpolicy="origin"></script>
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title')</title>
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/style_home.css">
    <link rel="stylesheet" type="text/css" href="/css/auth.css">
    <link rel="stylesheet" type="text/css" href="/css/predmet.css">
    <link rel="stylesheet" type="text/css" href="/css/print.css">
    <link rel="stylesheet" href="/font/circle/stylesheet.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
    <div id="content">
        <header>
            <div class="header-menu" >
                <div class="top-nav" id="myTopnav">
                        <a href="{{route('home')}}" class="top-nav__link"><img src="/img/logo.png" width="80px" alt="logotip"></a>
                        @auth
                        <a href="{{url('/account')}}" class="top-nav__link">Личный кабинет</a>
                        @endauth
                        @can('view-menu')
                        <a href="{{route('predm')}}" class="top-nav__link">Предметы</a>
                        @endcan
                        @can('add-post')
                        <a href="{{route('addnews')}}" class="top-nav__link">Добавить новость</a>
                        @endcan
                        @can('adminka')
                        <a href="{{route('home_admin')}}" class="top-nav__link">Админ-Панель</a>
                        @endcan
                            @auth                                
                                <a href="{{ url('/logout') }}" class="top-nav__link top-nav__link--btn"><div class="top-nav__btn-div">Выйти</div></a>
                            @else
                                <a href="{{ route('login') }}" class="top-nav__link top-nav__link--btn"><div class="top-nav__btn-div">Войти</div></a>
                            @if (Route::has('register'))
                                <a href="{{ route('register') }}" class="top-nav__link top-nav__link--btn"><div class="top-nav__btn-div">Регистрироваться</div></a>
                            @endif
                            @endauth
                
                        <a href="javascript:void(0);" class="top-nav__icon" onclick="myFunction()">
                        <i class="top-nav__icon-content icon-content"></i></a>
                </div>
            </div>
        </header>
        <main>
            <div class="wrapper">
                @yield('main_content')
            </div>
        </main>
    </div>
        <footer>
            <div class="footer">
                <div class="footer-container">
                    <div class="bottom-nav">
                        <a href="{{route('home')}}" class="bottom-nav__link bottom-nav__link--btn"><div class="bottom-nav__btn-div">Главная</div></a>  
                        <a href="{{url('/account')}}" class="bottom-nav__link bottom-nav__link--btn"><div class="bottom-nav__btn-div">Личный кабинет</div></a>
                        <a href="{{route('pechat')}}" class="bottom-nav__link bottom-nav__link--btn"><div class="bottom-nav__btn-div">О нас</div></a>
                    </div>  
                </div>
                <div class="footer-label"> 
                        ONschool Россия, Москва
                </div> 
            </div>
        </footer>
    <script  src="/js/func.js"></script>
</body>
</html>